### ISSUE TITLE
Newline at the end of example

### ISSUE THREAD

**Issue by sapegin** [azu/textlint-rule-eslint#1]
I’m trying to automate code formatting using textlint-rule-eslint and [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and it keeps adding new lines after each example. 

Would it make sense if textlint-rule-eslint strips new lines at the end or preserve the original number of new lines at the end? Prettier doesn’t have any setting for that (most likely it won’t) and ESLint [eol-last](http://eslint.org/docs/rules/eol-last) rule doesn’t work too because Prettier overwrites it.

**Comment by sapegin** [comment]
Looks like something is wrong here: it actually adds a new line every time I run `--fix`, not just once.

**Comment by azu** [comment]
Can you provide example?
I could't reproduce it.

> it actually adds a new line every time I run --fix, not just once.

What does that mean?


    ```js
    var a = "test";
    ```
    
`textint --fix` => 

    ```js
    var a = "test";

    ```

`textlint --fix` again =>

    ```js
    var a = "test";
    

    ```



If you get the above result, it is oddness.

**Comment by sapegin** [comment]
Sure: https://github.com/sapegin/textlint-rule-eslint-eof

**Comment by sapegin** [comment]
I did some debugging. The reason is that `node.value` is always trimmed:

```js
        var code = node.value;
```

**Comment by azu** [comment]
@sapegin Thanks!
I confirm it.

![textlint ast explorer 2017-05-14 23-37-27](https://cloud.githubusercontent.com/assets/19714/26034866/53c8cf9e-38fe-11e7-9d7d-e9193b9f6e75.png)
https://textlint.github.io/astexplorer/

textlint's markdown parser is based on http://remark.js.org/demo/ .
remark `Code` node's value always trim last `\n`.
Insteadof it, increase `Code`'s `end`.

![5 -14-2017 23-38-59](https://cloud.githubusercontent.com/assets/19714/26034877/9ea19758-38fe-11e7-86ff-663693234870.gif)

Probably, We can fix it that adding `\n` to `code` on https://github.com/azu/textlint-rule-eslint/blob/ca2e3ebaac0439d1be8283be562519257ccc87e7/src/textlint-rule-eslint.js#L29.

- https://github.com/wooorm/remark/issues/207
- https://github.com/syntax-tree/unist-util-source

**Comment by sapegin** [comment]
Awesome! I can make a PR for that.
